apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: pckhib/devops-capstone:blue
          ports:
            - containerPort: 80
