apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: pckhib/devops-capstone
          ports:
            - containerPort: 80
